"""empty message

Revision ID: c95a1ad5832b
Revises: 9ebbd67e0fa7
Create Date: 2024-02-24 17:56:30.758132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95a1ad5832b'
down_revision = '9ebbd67e0fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('access_expiration')

    # ### end Alembic commands ###
